### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Wintego** [b4iterdev/opencore-dell-inspriron-14-3467#2]
Hi, can you please update to latest versions of Monterey & OC?

**Comment by b4iterdev** [comment]
my device is currently running on HDD which is super-slow for it to even run High Sierra, opening syspref take about 30s or more so until I have a new SSD I won't update this EFI, but maybe you could try update kext.

**Comment by b4iterdev** [comment]
I have updated my EFI to Montery and lastest OC version and I will pushout to my repos tomorrow
