### ISSUE TITLE
Xin chào ! 
Mình xin lỗi vì viết tiếng việt nha, bạn có thay card wifi không ? Sao bên mình vẫn ko bắt đưocj wifi

### ISSUE THREAD

**Issue by quyld88** [b4iterdev/opencore-dell-inspriron-14-3467#3]

**Comment by b4iterdev** [comment]
Dạ bạn ơi mình dùng card wifi Intel(R) Dual Band Wireless AC 3165 từ máy xuất xưởng ạ và trong folder kext mình dùng Airportitlwm cho bản BigSur hay Monterey ạ. Do giờ mình không còn dùng máy đó nữa mà chuyển sang real mac nên là phiên bản Opencore đều cũ và kext cùng vậy, bạn có thể trước hết tải Airportitlwm mới nhất và tương thích với đúng phiên bản macOS mình đang dùng nha ạ: https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0
Nếu như mọi thứ đều ổn định thì bạn có thể thử update Opencore và kext, nếu các chức năng hoạt động bình thường thì bạn có thể gửi pull request nha

**Comment by quyld88** [comment]
Mình tải  rồi, nhưng không bật lên được, sao của mình lại là Card wifi QCA9377, hic mới search ra trên olalani là card này không hỗ trợ, mặc dù card này của mình cũng là xuất xưởng.

**Comment by b4iterdev** [comment]
Theo như https://dortania.github.io/Wireless-Buyers-Guide/unsupported.html thì có vẻ là QCA9377 không có kext cho macOS ạ, khả năng là card wifi do các bên xuất xưởng sử dụng khác nhau ạ. A có thể tìm mua card intel giờ cùng rất rẻ, hoặc tìm card realmac để có mấy tính năng continuity ạ

**Comment by quyld88** [comment]
> Theo như https://dortania.github.io/Wireless-Buyers-Guide/unsupported.html thì có vẻ là QCA9377 không có kext cho macOS ạ, khả năng là card wifi do các bên xuất xưởng sử dụng khác nhau ạ. A có thể tìm mua card intel giờ cùng rất rẻ, hoặc tìm card realmac để có mấy tính năng continuity ạ

À, vậy giờ máy mình nên mua card realmac ntn , rồi hình như cần adaptor để chuyển chứ đúng ko bạn ?
Bạn thử làm lần nào chưa ?

**Comment by b4iterdev** [comment]
https://dortania.github.io/Wireless-Buyers-Guide/Airport.html
Ở đây là list những card realmac để a có thể tham khảo ạ, và nó cũng cần adapter do giao thức của nó không giống các card thông thường cần có cổng chuyển để hoạt động được ạ. 
Đây cá nhân em thấy là option cho ai vẫn muốn dùng hackintosh và không gặp rào cản kinh tế =))) hầu hết mọi người sẽ tìm card wifi mà nó có cùng chipset với card realmac (không phải card realmac mà chỉ chung chipset như BCM...) và sẽ cần phải thêm kext để tương thích, còn đâu gần như continuity không được ngon như realmac nma nó còn hoạt động được ạ

**Comment by b4iterdev** [comment]
Còn thực tiễn, nếu có thể thì em nghĩ là Hackintosh nên chỉ là phương pháp giúp mình được trải nghiệm macOS thui ạ, còn như em dùng một thời gian thấy thích hợp nên em mua luôn macbook dùng cho thích á, ổn định hơn, touchpad to gần như chả ai dùng chuột với nó, ... giờ chip Apple silicon chạy ngon lắm rồi ạ

**Comment by quyld88** [comment]
Cảm ơn em nha, anh có thể kết bạn với em qua facebook hay telegram ko ?

**Comment by b4iterdev** [comment]
được a ơi, anh gửi kết bạn qua fb ở trên pro5 github của em nha ạ
